build site:
  image: node
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node
  stage: test
  script:
    - npm install --progress=false
    - npm run unit

e2e test:
  image: node
  stage: test
  script:
    - npm install --progress=false
    - npm run e2e
    
code quality:
  image: node
  stage: test
  script:
    - npm install --progress=false
    - nmp run lint