name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
        tag_with_sha: true
        repository: crowdcontrol/frontend
        push: true
  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy
      uses: floms/action-caprover@v1
      with:
        host: 'https://captain.app.crowdcontrol.network'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        app: 'crowdcontrol-frontend'
        image: 'crowdcontrol/frontend'
