name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DockerUsername }}
        password: ${{ secrets.DockerPassword }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crowdcontrol/frontend:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
  deployment:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
    - name: Deploy to Server
      uses: floms/action-caprover@v1
      with:
        host: 'https://captain.app.crowdcontrol.network'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        app: 'crowdcontrol-frontend'
        image: 'crowdcontrol/frontend:${{ github.sha }}'
