on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  LABEL: ${{
    contains(github.event.pull_request.labels.*.name, 'deploy_5173') && 'deploy_5173' || 
    (contains(github.event.pull_request.labels.*.name, 'deploy_5174') && 'deploy_5174' || 'none')
    }}


jobs:
  run_pull:
    if: ${{ env.LABEL != 'none' }}
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        echo env.tag_name
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.LXGR_DEPLOY_PRIV }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.LXGR_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.LXGR_USER }}@${{ secrets.LXGR_HOST }} "cd ~/$LABEL && git fetch && git checkout ${{ github.event.pull_request.base.ref }} && git pull && npm i && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
