name: Test CD

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    env:
      # Setting an environment variable with the value of a configuration variable
      LABEL: ${{
        contains(github.event.pull_request.labels.*.name, 'deploy_5173') && 'deploy_5173' || 
        (contains(github.event.pull_request.labels.*.name, 'deploy_5174') && 'deploy_5174' || 'none')
        }}

    steps:
      - name: install liefer
        if: ${{ env.LABEL != 'none' }}
        run: |
          go install github.com/lxgr-linux/liefer@latest
      - name: deploy
        if: ${{ env.LABEL != 'none' }}
        run: |
          ~/go/bin/liefer deliver $LABEL ${{ github.event.pull_request.head.ref }} ${{ secrets.LIEFER_PRIVKEY }} --address ${{ secrets.LXGR_HOST }}:8080
